# Site settings
title: 
header-img: img/home-bg.png
email: cathy.y.lii@gmail.com
copyright_name: catzlii14
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  catzlii14
learn_profile: catzlii14
email_username: cathy.y.lii@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
